# Generated by Django 2.2.7 on 2019-11-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0002_auto_20191118_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detail',
            field=models.TextField(default='Input'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.TextField(default='Input'),
            preserve_default=False,
        ),
    ]
