# Generated by Django 2.2.7 on 2019-11-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0007_auto_20191125_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shop',
        ),
    ]
