# Generated by Django 2.2.7 on 2019-11-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_item_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shop',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
