# Generated by Django 2.2.7 on 2019-11-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0012_auto_20191125_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('B', 'Books'), ('FB', 'Food and Beverage'), ('A', 'Artisans'), ('AW', 'Art Work'), ('FW', 'Foot Wear'), ('D', 'Drugs'), ('F', 'Fashion')], max_length=2),
        ),
    ]
