# Generated by Django 2.2.7 on 2019-11-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0013_auto_20191128_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='shop',
        ),
    ]
